### ISSUE TITLE
[BUG] 当前是第 0 帧的时候 play() 播放倒放不了

### ISSUE THREAD

**Issue by 1014156094** [vmllab-js/FramePlayer#16]
[BUG] 当前是第0帧的时候播放倒放不了
预期效果：应该从最后一帧倒序播放到第 0 帧

**Comment by RhineLiu** [comment]
play(startFrame, endFrame, options)
startFrame可以设置成比endFrame大的帧值，这样能倒放
如果想从最后一帧倒序播放到第 0 帧，startFrame为length-1，endFrame为0
